# Generated by Django 4.2.3 on 2023-07-07 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('rating', models.IntegerField(default=0)),
                ('cider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flavors', to='main_app.cider')),
            ],
        ),
    ]
